# Generated by Django 5.1.15 on 2026-06-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('year_range', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(default='Executive Chef', max_length=200)),
                ('bio', models.TextField()),
                ('philosophy', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chefs/')),
                ('image_url', models.URLField(blank=True)),
                ('accent_image', models.ImageField(blank=True, null=True, upload_to='chefs/')),
                ('accent_image_url', models.URLField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('michelin_stars', models.PositiveIntegerField(default=0)),
                ('awards_count', models.PositiveIntegerField(default=0)),
                ('cookbooks_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chef',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_desc', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('image_url', models.URLField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date_display', models.CharField(blank=True, help_text='e.g. "Every Friday"', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('ambiance', 'Restaurant Ambiance'), ('food', 'Food Photography'), ('events', 'Events'), ('team', 'Our Team')], default='food', max_length=30)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('starters', 'Starters'), ('seafood', 'Seafood'), ('main', 'Main Course'), ('steaks', 'Steaks'), ('desserts', 'Desserts'), ('beverages', 'Beverages'), ('signature', 'Signature'), ('seasonal', 'Seasonal Specials')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (used if no file uploaded)')),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_halal', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_chef_pick', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('18:00', '6:00 PM'), ('18:30', '6:30 PM'), ('19:00', '7:00 PM'), ('19:30', '7:30 PM'), ('20:00', '8:00 PM'), ('20:30', '8:30 PM'), ('21:00', '9:00 PM'), ('21:30', '9:30 PM'), ('22:00', '10:00 PM')], max_length=10)),
                ('guests', models.PositiveSmallIntegerField(default=2)),
                ('seating', models.CharField(choices=[('main', 'Main Dining Room'), ('private', 'Private Room'), ('chefs', "Chef's Table"), ('terrace', 'Terrace'), ('bar', 'Bar & Lounge')], default='main', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('occasion', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('confirmation_no', models.CharField(blank=True, max_length=12, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('quote', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('avatar_url', models.URLField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
